### ISSUE TITLE
Two New Possible Datasets - STANDBY

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#100]
Thinking neighborhoods would find it useful to be able to look up 311 sidewalk calls in their area plus problem rentals/slumlords... Waiting to identify OpenData dataset. standby...

**Comment by AmandaWilsonKC** [comment]
Okay - Could we do another calculation that identifies potential rental properties? I think we could compare owner address data to the property address data and if it's different then it could be flagged as a potential rental property. Then if we combine that with code violations then we have a list of potentially problem landlords! Voila!

**Comment by JakeLaCombe** [comment]
Sounds great! That doesn't sound like a vacancy issue to me, so I'll add on a new tab to display that data.

**Comment by JakeLaCombe** [comment]
Added in the miscellaneous tab. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/a4b52e93e2e038dd8c1c2b415da795fc65b4e5b1
