### ISSUE TITLE
Change Name of Landbank Filter

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#101]
Please change "Vacant Lot - Land Bank Property (City of KCMO)" to "Vacant Property - Land Bank Property (City of KCMO)"

That was our bad for having the wrong title in the dataset attribute xls.

**Comment by AmandaWilsonKC** [comment]
Update - can we actually get TWO separate filters for the land bank data - one for land bank lots and one for land bank properties with buildings? This information is the Property Condition column of the open data at https://data.kcmo.org/Property/Land-Bank-Data/2ebw-sp7f/data.

- Vacant Building - Land Bank Property (City of KCMO) - Property Condition column would include the words "Structure"
- Vacant Lot - Land Bank Property (City of KCMO) - Property Condition column would include the words "Vacant Lot or Land"

Being able to differentiate between a lot or building owned by the Land Bank is super helpful for neighborhoods.

**Comment by JakeLaCombe** [comment]
Done. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/d8207976df1a7ff859cbbc8e876cf619d0d2a62d
