### ISSUE TITLE
311 Sidewalk Data

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#102]
Would it be easy enough to add 311 Sidewalk Data, either to the vacancy tab or a new tab? 

https://data.kcmo.org/311/311-Call-Center-Service-Requests/7at3-sxhp - Under the Work Group column there's an option to pull "Public Work-Capital Projects-Sidewalks"

**Comment by JakeLaCombe** [comment]
That looks pretty cool! It looks like it should be easy to consume, as I see a neighborhood column in the dataset. What matters though is how it's used?

What is the goal of the Sidewalk data? Is it to show an indication of vacancy, or is it to just show sidewalks that need work done?

**Comment by AmandaWilsonKC** [comment]
Based on my neighborhood association, it would be helpful to see where bad sidewalks are already noted so neighborhoods can 1) see where else they need to report a bad sidewalk in order to get a sidewalk fixed, and 2) work with the city to get sidewalks fixed using the GO Bond money. 

Should only pull incidents that are still open (labeled as open in the status column)

Data filter name: Sidewalk Repair Requests (KCMO 311)
For tooltip, would include: Address, creation date, case ID

**Comment by JakeLaCombe** [comment]
Done! https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/b5eaae41c69469afe1317790fcf97c0510335437

Try it out! Go to http://www.kcneighborhoodstat.org/neighborhood/235/misc, and click on the filters.
