### ISSUE TITLE
Select Diff Neighborhood Without Clicking on the KCNeighborhoodStat

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#107]
So. Could it be possible to click from neighborhood to neighborhood without having to first click on the KCNeighborhoodStat logo to reset?

**Comment by JakeLaCombe** [comment]
I think so. How would you like the UX of it to play out? Do you want the currently selected neighborhood to have a different shaded color? Perhaps give that the dark color, and give surrounding neighborhoods a different shade?

**Comment by JakeLaCombe** [comment]
I implemented it here. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/2f1852664ada1ad3c8ad35a256bf6d9b8f511023 We can re evaulate if this new approach works for us.
