### ISSUE TITLE
Ability to Export Search Results 

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#110]
It would be really helpful if users can export the results from their queries. I think just exporting the information that's in the tooltip would suffice.

**Comment by JakeLaCombe** [comment]
That should be possible. How would you like the output to display?

**Comment by AmandaWilsonKC** [comment]
I guess the export could just display the information in the tooltip as the columns? Was there anything else you were looking for?

**Comment by JakeLaCombe** [comment]
I was thinking you wanted a spreadsheet, csv file, json endpoint, something like that.

**Comment by AmandaWilsonKC** [comment]
Ah, yes, I suppose a xls or csv would standard. Could we also export a pdf or jpg of the map and key? I would imagine being able to export a map that lists property addresses would be really helpful. That doable??

**Comment by JakeLaCombe** [comment]
@AmandaWilsonKC I've exported the PDF of the map with the various tooltips in this commit. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/a7c147a9c842032d72f09980adde21b177072d7f
Try it out! Just go to a vacancy tab, check some filters, and hit export!

I do have some caveats though. Google Maps will only allow for so many markers to be produced at once, so if there are too many data points, then an image will not be produced. Would you have an alternative solution that you would like for this scenario?

**Comment by JakeLaCombe** [comment]
Closing with limitation. If other issues persist, we can just open a new one.
