### ISSUE TITLE
NaN appears in Neighborhood -> Crime -> Report totals

### ISSUE THREAD

**Issue by Nerdenator** [codeforkansascity/Neighborhood-Dashboard#118]
<img width="912" alt="screen shot 2017-06-07 at 9 49 23 am" src="https://user-images.githubusercontent.com/5439509/26884923-a7bc117c-4b66-11e7-804a-c16a9aa6c2ad.png">

Possibly because of Extortion being NaN?

Exists on issue-115 branch as of 9:50 AM on 6-7-2017

**Comment by JakeLaCombe** [comment]
Not seeing this on master. Perhaps the branch has a defect?

**Comment by Nerdenator** [comment]
it almost certainly is this branch, i'll have to investigate it next week-ish

**Comment by JakeLaCombe** [comment]
Confirmed it's on your branch. Closing
