### ISSUE TITLE
Meetup 7/27: Minutes and Week Ahead 

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#13]
### Meetup Minutes

* Clarified basic functionality: *Determined how the user would navigate within a neighborhood page, between categories and subcategories. A sketch of this layout is provided below, showing the two levels of tabs. Main category tabs -- at this point Safety, Demographics, Housing, Development, and Vacancy -- would break down into 2-4 "subtabs." In the example below, these subtabs would be Crime and Sex Offenders.* 

![nstat tabs sketch](https://cloud.githubusercontent.com/assets/12629402/8938432/467844bc-3524-11e5-8fcc-2ec0e0460321.jpg)

* Went through prototype layouts of each category, pictured below. *Vacancy tab has not yet been discussed.* 

**~~Crime~~ tab** Safety tab, actually (Crime would be a "subtab" under Safety.)
![image](https://cloud.githubusercontent.com/assets/12629402/8921006/2653203c-3496-11e5-9c57-2473cabc9236.png)

**Demographics tab**
![image](https://cloud.githubusercontent.com/assets/12629402/8921015/40d322fe-3496-11e5-8560-29c32ebb2eec.png)

**Housing tab**
![image](https://cloud.githubusercontent.com/assets/12629402/8921027/645e6314-3496-11e5-9cfc-2e5300ef1ebb.png)

**Development tab**
![image](https://cloud.githubusercontent.com/assets/12629402/8921024/517f3f8e-3496-11e5-9de5-f15136340524.png)

### To Do - The Week Ahead

*Heather:*
- [ ] Clean up prototype, especially for crime 

*Jake:* 
- [ ] Begin Safety tab, based on wireframes from Heather

*Ben/Amanda (CCF):* 
- [ ] Determine datasets for "Vacancy"

- [ ] Update spreadsheet with Property Violation data

**Comment by JakeLaCombe** [comment]
Would the Safety Tab correlate to the Crime Tab you have at the top? @BenCCF

**Comment by BenCCF** [comment]
Good question. That tab should actually be "Safety". Crime would be one of the "sub tabs" beneath it, along with another for sex offenders. I'll correct that above.

**Comment by JakeLaCombe** [comment]
@HDchemistry how will the correspond to the PDF's you sent me? I take it that I should create a neighborhood page to have just these tabs and small tabs with a banner identifying the neighborhood name?

**Comment by HDchemistry** [comment]
@JakeLaCombe I will send you the cleaned up PDFs today.

**Comment by JakeLaCombe** [comment]
Our general mockups are complete for the project. We can close this issue
