### ISSUE TITLE
Tweaks to display text

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#132]
1. The legend for the all properties that show up when you click on the LEgally Abandoned checkbox (under VAcancies tab) should read "Weak Case for Abandoned Housing Act", "Medium Abandoned Housing Act Case" "Strong  Abandoned Housing Act Case", and "Very Strong Abandoned Housing Act Case". This legend does not need the description "Circle - Vacant Building, Polygon - Vacant Lot"

2. There doesn't need to be a legend visible When you click on one of the boxes under the Vacant Indicators list (under the Vacancies tab).

3. In the tooltip, can the owner name and address (this may be different than the site address) be displayed whenever you click on a filter in the Vacant Indicators list?

4. In the export pdf feature, can the list of properties be numbered sequentially? Right now the report numbers properties 1-9, then a-z, then starts over. It's a really useful report but weird how the properties are listed.

5. Under the Miscellaneous tab, can you change the filter Potential Problem Renters to "Potential Problem Landlords (Rental properties with code violations)"?

Let me know if you have any questions. Thank you!

**Comment by AmandaWilsonKC** [comment]
Another addition for the Vacancies tab:
The tooltip for 311 data should have the header "KCMO 311 Data", not "Three Eleven Data"

This tooltip appears when a users selects any of the three filters: Vacant Structure (KCMO 311), 311 Open Cases (KCMO 311), All Property Violations (KCMO 311).

Thanks!

**Comment by moldybeats** [comment]
These changes are done & deployed, except for item 3 ("In the tooltip, can the owner name and address (this may be different than the site address) be displayed whenever you click on a filter in the Vacant Indicators list?"). This is a more involved change than the others, so I spun it off into its own ticket (#150) and I'll close this one.
