### ISSUE TITLE
Homepage Takes a While to Load

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#134]
The homepage takes a while to load when you navigate to the site. Any way this can be fixed to load more quickly? Thanks!

**Comment by JakeLaCombe** [comment]
We will need paid hosting to accomplish that. They way Heroku free tier works is that if shuts down the box if no one uses it for awhile.

**Comment by AmandaWilsonKC** [comment]
thanks. do you have any recommendations for paid hosting? wasn't that something @zmon and Code for KC was looking into?

**Comment by zmon** [comment]
Please talk to me this Monday and we will get you setup.

**Comment by AmandaWilsonKC** [comment]
Thanks Paul!
