### ISSUE TITLE
Need permanent place to host website

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#136]
@zmon please help us at a hack night. thank you!

**Comment by buzwells** [comment]
I think we've got this in the form of the Heroku deployment. We have a separate issue for obtaining a more long-term domain name, but we have the hosting platform for now (thanks to @zmon).

On that basis, I'll close the issue. But feel free to reopen if I'm incorrect about that.
