### ISSUE TITLE
Address API: Will it account for changing Census boundaries?

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#14]
Amanda and I have been discussing displaying certain Census data across time, not just for the 2010 count. We'd want to display 2013 estimates (when available), as well as 2000 counts. Census geography boundaries don't change between 2010 and 2013. However, in many cases, boundaries do change between 2010 and 2000. 

Is it feasible to associate addresses with 2000 Census boundaries? What would we need to make that happen?

**Comment by JakeLaCombe** [comment]
Most mapping api's want pairs of latitude and longitude to draw the appropriate shape on the map. While we may have access to that data, I don't know if any mapping API's store maps of given years. Overtime,  neighborhoods can add and destroy roads, which may throw off your coordinates and neighborhood boundaries.

**Comment by zmon** [comment]
We will see if we can attache both.  Created codeforkansascity/address-api#15

**Comment by BenCCF** [comment]
Great.


________________________________

**Comment by JakeLaCombe** [comment]
@HDchemistry how will the correspond to the PDF's you sent me? I take it that I should create a neighborhood page to have just these tabs and small tabs with a banner identifying the neighborhood name?

**Comment by JakeLaCombe** [comment]
@HDchemistry how will the correspond to the PDF's you sent me? I take it that I should create a neighborhood page to have just these tabs and small tabs with a banner identifying the neighborhood name?

**Comment by JakeLaCombe** [comment]
Implemented Here. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/ac507d8893d819e3fd674488fb0c64665ba8e96e
