### ISSUE TITLE
Meetup 8/10 Update

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#15]
We didn't meet at the 8/3 event, for the record. 

This week, though, we got mock up for a Safety "tab" on to Jake, and he began building. We were able to find a list of NIBRS codes by "Crime Against" category (https://www.fbi.gov/about-us/cjis/ucr/nibrs/nibrs-user-manual, page 14) -- along with the mock-up, this was probably the biggest 
piece of the puzzle needed to get Jake building.  

H and @BenCCF discussed mock-ups for other pages/tabs. Besides tweaks to individual pages, 

A couple of more major issues/conclusion emerged by evening's end:

- First, while we're still moving ahead with a "tabs" scheme (described in the last meeting's summary), we're considering doing away with the subtabs within each main tab. To illustrate, instead of breaking the main "Demographics" tab into separate subtabs for population, race, income, age, etc., each suptopic would be displayed by default at once as separate "cards". H's mock-ups of a few main tabs suggest we could pull this off while keeping all the data legible. 

- Second, the Address API is going to be crucial moving forward. Jake was essentially able to associate the addresses of crime reports to ZIP codes. Getting the addresses linked to neighborhoods will require use of the Address API. 

For this next week:

- [ ] @JakeLaCombe: Whatever progress on the Crime tab possible. Also, maybe get with Paul re: any work needed on the API.

- [ ] Heather: Continued progress on mock-ups  

- [x] CCF's end: Prepping to reach out to demographic researcher at UMKC to get some answers on how best to deal with/present some of our data

**Comment by JakeLaCombe** [comment]
We've talked a lot about these tabs, and have implemented the features mentioned here. Let's close this
