### ISSUE TITLE
Document Vacant Indicators

### ISSUE THREAD

**Issue by moldybeats** [codeforkansascity/Neighborhood-Dashboard#154]
Look into the queries behind the various Vacant Indicators (on the Vacancies tab) and document what each of them is pulling from the various datasets. Once we have that documented, it might be good to add an icon/tooltip to explain those for anyone unfamiliar with the app.

**Comment by moldybeats** [comment]
The vacant indicators pull their data from the following sources:

- Vacant Building: [KCMO Land Bank Data dataset](https://data.kcmo.org/Property/Land-Bank-Data/2ebw-sp7f) where property_condition like 'Structure%'  *(note that the Source on these is misidentified in the UI as the Dangerous Building dataset)*
- Vacant Lot: [KCMO Land Bank Data dataset](https://data.kcmo.org/Property/Land-Bank-Data/2ebw-sp7f) where property_condition like 'Vacant lot or land%'  *(note that the Source on these is misidentified in the UI as the Dangerous Building dataset)*
- Demo Needed: [KCMO Land Bank Data dataset](https://data.kcmo.org/Property/Land-Bank-Data/2ebw-sp7f) where demo_needed = 'Y'
- Failure to Register as Vacant: [KCMO Property Violations dataset](https://data.kcmo.org/Housing/Property-Violations/nhtf-e75a) where violation_code = 'NSVACANT'
- Vacant Structure: [KCMO 311 Call dataset](https://data.kcmo.org/311/311-Call-Center-Service-Requests/7at3-sxhp) where request_type in ('Animals / Pets-Rat Treatment-Vacant Home','Animals / Pets-Rat Treatment-Vacant Property','Cleaning vacant Land Trust Lots','Mowing / Weeds-Public Property-City Vacant Lot','Nuisance Violations on Private Property Vacant Structure','Vacant Structure Open to Entry')
- 311 Open Cases: [KCMO 311 Call dataset](https://data.kcmo.org/311/311-Call-Center-Service-Requests/7at3-sxhp) where status='OPEN'
- KCMO Dangerous Buildings: [KCMO Dangerous Buildings dataset](https://data.kcmo.org/Property/Dangerous-Buildings-List/ax3m-jhxx) (no conditions)
- Vacant and Boarded: [KCMO Property Violations dataset](https://data.kcmo.org/Housing/Property-Violations/nhtf-e75a) where violation_code = 'NSBOARD01'
- Tax Delinquent: [CodeForKC Address API](http://dev-api.codeforkc.org/api-docs/) which includes county_delinquent_tax_[year] fields for each year

**Comment by zmon** [comment]
You might think about adding this to the readme.

**Comment by AmandaWilsonKC** [comment]
- Vacant Building: KCMO Land Bank Data dataset where property_condition like 'Structure%' (note that the Source on these is misidentified in the UI as the Dangerous Building dataset) - In the UI, the Source link is directed to Dangerous Buildings, not KCMO Land Bank dataset. Can you please rename in the UI Filter tab "Land Bank Property with Building (City of KCMO Land Bank Data)"
- Vacant Lot: KCMO Land Bank Data dataset where property_condition like 'Vacant lot or land%' (note that the Source on these is misidentified in the UI as the Dangerous Building dataset) - In the UI, the Source link is directed to Dangerous Buildings, not KCMO Land Bank dataset. Can you please rename in the UI Filter tab "Land Bank Property - Vacant Lot, No Building (City of KCMO Land Bank Data)" 
- Demo Needed: KCMO Land Bank Data dataset where demo_needed = 'Y' - In the UI, the Source link is directed to Dangerous Buildings, not KCMO Land Bank dataset. Can you please rename in the UI Filter tab "Land Bank Property with Demo Needed (City of KCMO Land Bank Data)" 
- Failure to Register as Vacant: KCMO Property Violations dataset where violation_code = 'NSVACANT' - Change on Filter tab to say "Failure to Register as Vacant (City of KCMO **Property Violations Data**)

**Comment by moldybeats** [comment]
- Documented the source of the various vacancy indicator filters in the README file
- Changed the 4 filter names as requested above
