### ISSUE TITLE
Automatically Show Filters when switching between tabs

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#156]
Can we show the filters automatically when switching between tabs (like the demographics tab)? This would delete the Filter button. 

Can you also change the Done button on the filters to "Apply"?

**Comment by moldybeats** [comment]
I changed it so that the filters tooltip on the Crime, Vacancy and Misc. tabs will be open by default when you switch between tabs. It will disappear when you choose your filters so as not to cover up too much of the map. See if you like how that works.
