### ISSUE TITLE
Show Years Tax Delinquent when open Source data

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#158]
IN the vacancy tab, when you run the Legally Abandoned query and click on the source for Tax Delinquency, it takes you to a crazy scrambled looking page. Can that be simplified to just show the years that the property is tax delinquent? Thanks!

**Comment by moldybeats** [comment]
@zmon - Paul, I see some work in the address-api repo around a `tax-delinquency` endpoint, which might be useful here, but it doesn't seem like it's currently exposed (according to the [API docs](http://dev-api.codeforkc.org/api-docs/)). Is that something we could use for this?

**Comment by zmon** [comment]
@moldybeats it is in the county endpoint.  Now that you bring it up it should be its own endpoint.  http://dev-api.codeforkc.org/api-docs/#!//get_address_attributes_county_id_version_CountyID

Do that solve your issue?

**Comment by moldybeats** [comment]
@zmon - yes, the county data is what I needed. Thanks!

I think we'll need to create a little page that displays only the tax delinquency info from the county data in a more readable format (rather than the JSON response from the address API) so it's usable for non-tech folks looking for the source of this info.

**Comment by moldybeats** [comment]
This is done. When you click on the Source link for tax delinquency, it shows a simple page with just the tax delinquency info for that address. It's nothing fancy right now, so if we need to spruce it up a bit we can.
