### ISSUE TITLE
Meetup 8/17

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#16]
### Mockup Updates
Heather updated us on her progress on mockups. Here is the latest general layout of a neighborhood page: https://files.slack.com/files-pri/T0423273A-F097L3VMF/mockups_august_17.jpg. Subtabs are back for now. (We had discussed switching to a "cards" format last week -- the tabs, though, might work better for organizing at least certain data with many subcategories.)

### Coding: Crime tab
@JakeLaCombe began working from the mockups, adapting the layout. He also said he should be able to complete the Crime tab by the August 31st Project Fair.

We also got some valuable input from @zachflanders via Slack regarding using bounding boxes to select points. This could have an application for pages like the Crime, when crime reports need to associated with a polygonal geography. 

### Vacancy tab
We also discussed the potential components of the planned Vacancy tab, the next tab we would like developed. Heather will work those into a mock-up. 

To further refine the components, we have asked Peter Hoffman of Legal Aid of Western MO to join us next Monday. He should be able to explain how certain data should be displayed.

### Staying in contact going forward
I (@benCCF) will not be attending Monday-night meetups from now on, on account of the semester starting (specifically an evening class Monday nights). I will still kind of be steering things from afar and will be communicating by Slack and GitHub. Likewise, please communicate with me through those channels. @amandaCCF will still be attending Hack Nights, so if you can still attend, please do so!

(@zmon Still trying to get Heather here on Github. )

**Comment by JakeLaCombe** [comment]
Mockups have been completed. We can close this.
