### ISSUE TITLE
Meetup 8/24/15

### ISSUE THREAD

**Issue by amandaCCF** [codeforkansascity/Neighborhood-Dashboard#17]
<b>Crime Tab</b>
@JakeLaCombe and @zachflanders fixed the Crime API in the application and started architecting the heatmap.

<b>Vacancy/Property Tab</b>
Heather and @amandaCCF worked with Peter Hoffman with Legal Aid of Western Missouri to identify the data most useful for his organization and neighborhoods and how it should be presented. Heather will use that to rework the mockups.

<b>UNI presentation</b>
@amandaCCF and @zmon will present to the Urban Neighborhood Initiative’s Partners Meeting on Tuesday, Aug 25 to tell them about the app, get feedback on their data needs, and hear how they will use the data.

<b>Hack KC Mid-Point Presentation</b>
@BenCCF and @amandaCCF will be putting together a short presentation for the midpoint roundup that will also include a demo of the crime tab.

**Comment by JakeLaCombe** [comment]
We have the crime tab working with different tooltips and tooltip descriptions.
