### ISSUE TITLE
Code Violation Scoring/Weight

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#18]
We’re trying to find a way to display the “severity” of code violations – the more severe, the more likely that the neighborhood/City could begin legal proceedings. Peter with Legal Aid went through different types of code violations and scored them, from weakest (1) to strongest (3). He adds, “I do think we need to come up with some sort of formula however. Having ten #1's is obviously just as bad as having one #3. Something to think about I suppose.”

Check out Peter's scoring here: https://codeforkc.slack.com/files/benccf/F0A2AK6G4/code_citation_rankings_lawmo.pdf

Let's think about a scoring formula and discuss soon. Feel free to post your ideas. I will be looking into best practices for this kind of thing over the next few weeks.

@amandaCCF

**Comment by JakeLaCombe** [comment]
Do we have notes from our meeting at Thou Mayest? Let's post them here so that we don't forget!

**Comment by amandaCCF** [comment]
Here's my notes. Wish i would've edited them and summarized what we decided on how we're depicting things using shading and dots. :\

[20160212160822302.pdf](https://github.com/codeforkansascity/Neighborhood-Dashboard/files/128806/20160212160822302.pdf)

**Comment by JakeLaCombe** [comment]
We did the coding here for the project. This feature can be marked as done for now.

https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/4bdbe6678db44703c5f573c350e476a5716d09c6
