### ISSUE TITLE
Inconsistency in crime data display 

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#19]
@JakeLaCombe @zachflanders @zmon 

Possible bug.

I noticed today crime data is displaying inconsistently across neighborhoods. In the photo attached, I've got screenshots of the crime display from three different neighborhoods.

There are two possible issues here. First, many years appear to have zero crime reports. This would maybe be understandable for years farther back since we might not have data for those years, but here, it's the last few years that are missing reports. Second, the point at which reports disappear seems to be different, too, if you compare Quality Hill and West Plaza, for instance. 

And maybe another issue -- In the screenshot, Ivanhoe has no crime displayed. 

Would one of you have a look so we can try to understand whether this something on our end or an issue with the data? Is this something that would be solved with the Address API? 
![crime data display 9-2](https://cloud.githubusercontent.com/assets/12629402/9638648/7b8923fa-516d-11e5-95fa-4d6e9a770d53.jpg)

@amandaCCF

**Comment by BenCCF** [comment]
@amandaCCF @JakeLaCombe Could you discuss what's happening with the crime data display at tonight's meetup?

**Comment by JakeLaCombe** [comment]
We will look into this. I'll have to see if we fixed the issue with the API not taking in the correct polar requirements.

**Comment by JakeLaCombe** [comment]
I think we will be moving Crime Data off the app. Even with the crime data, we are not currently using this TrendingChart. We can close this bug for now.
