### ISSUE TITLE
Implement AngularJS on top of rails

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/Neighborhood-Dashboard#20]
Our app is starting to look better as a single page application. As such, it's highly advised we put angular on top of our rails stack.

**Comment by briansully1** [comment]
New to Code for America.
I've been to two meetings.
Where can I post a bio 
To the people in this group

**Comment by briansully1** [comment]
I just subscribed so I suppose I'll get an email thanks anyhow

**Comment by zmon** [comment]
@briansully1 can you email me at pbarham@codeforamerica.org

**Comment by JakeLaCombe** [comment]
I believe the angular incorporation is complete. This commit gives us two different switchable tabs to work with.

https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/78e25f62246f0801e47e2f725480085c6b207ddd
