### ISSUE TITLE
Add Error Messages for when a Neighborhood isn't found or the dataset errors out

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/Neighborhood-Dashboard#28]
There will be instances when a given neighborhood isn't found in the site. We need to throw toasted messages to the user to show them when this happens.

**Comment by JakeLaCombe** [comment]
To easily implement this, we should stick to angular-flash. http://sachinchoolur.github.io/angular-flash/

**Comment by JakeLaCombe** [comment]
Make sure you import it to the bower file, and then import it inside the application.js file appropriately

**Comment by derekprovance** [comment]
Hey guys, making progress on this. Should be posting it sometime tonight

**Comment by JakeLaCombe** [comment]
It's finished at the following commit. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/67a41a9c8896313a8bf35901c348a3728b7cae9d
