### ISSUE TITLE
MVP: Add Sex Offenders to the Crime Map

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/Neighborhood-Dashboard#32]
The crime map should contain the ability to add and remove sex offenders from the neighborhood. 

What we first need to do is determine what dataset we would like to pull from. data.kcmo.org doesn't appear to have any of that data, so I'm not sure if it's something that can be added there, or if we should look for other possible resources. @zmon

**Comment by EricRoche** [comment]
@JakeLaCombe Data does not come from the City.

**Comment by JakeLaCombe** [comment]
@AmandaWilsonKC How does this page look? If you notice on the top, there is a file that can be downloaded.

**Comment by JakeLaCombe** [comment]
Moving off first release. We don't have a good way to import this data right now.

**Comment by JakeLaCombe** [comment]
I'm going to actually close this issue. Given that we can't get reliable up to date data for this in a consistent manner, this produces a major liability or us.
