### ISSUE TITLE
Angular version mismatch with angular-route and angular-resource

### ISSUE THREAD

**Issue by patrickhousley** [codeforkansascity/Neighborhood-Dashboard#37]
Angular moduls like angular-route and angular-resource are typically the same version as angular itself in any given project. Is there a particular reason why the version of these two dependencies do not match the angular dependency version? Does anyone have a preference on upgrading to angular 1.4.9?

**Comment by JakeLaCombe** [comment]
I'm fine with uplifting to angular 1.4.9. Feel free to submit a pull request to make the change!

**Comment by JakeLaCombe** [comment]
Looks like the uplift is already done, and was done here. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/d87caa3c9a454313f0cbe7749d2b243ce3201ed3
