### ISSUE TITLE
Neighborhood api index response

### ISSUE THREAD

**Issue by patrickhousley** [codeforkansascity/Neighborhood-Dashboard#41]
I have noticed that the API result of neighborhood/index and neighborhood/show are the same when using address "18th and Vine". I am curious if the data response from neighborhood/index is redundant. Is there an instance where the response from neighborhood/index could have any other action than to take the user to a specific neighborhood or to leave the user on the homepage? Is it possible for an address to exist in more than one neighborhood within the dataset?

If the answer to these questions is now, I suggest the neighborhood/index API be modified to return only the ID of the neighborhood or maybe the IDs of the neighborhoods found. This results in less data coming across the pipe and a slightly more performant user experience.

**Comment by JakeLaCombe** [comment]
The index route is primarily used for searching for neighborhoods, whereas the show view is designed to show the entire page for a neighborhorhood, just like you suggested.

Given that we would like to potentially migrate to a select2 box for a dropdown of prepopulated neighborhoods, I like your suggestion. I think we may also need to add the name of the neighborhood to the index for display purposes, but that can come at a later point..

**Comment by JakeLaCombe** [comment]
Also, I believe I'm using a google mapping tool for the neighborhood searching from an address, meaning I think it will only be apart of one neighborhood.

**Comment by patrickhousley** [comment]
All good to hear. I recommend the angular ui-select dependency for implementing a select2 box. If you have not looked at it, the selectize theme is also very nice for selects. Overall, a select is definitely a step in the right direction but I think we should still provide users a method of entering an address in case they don't know what neighborhood the are in (it could happen :) ).

**Comment by JakeLaCombe** [comment]
Agreed as well.

**Comment by JakeLaCombe** [comment]
I think we got this addressed in https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/115f1c9c1de21b94a014ba815f102f1e83a43c13
