### ISSUE TITLE
Neighborhood page wireframe

### ISSUE THREAD

**Issue by patrickhousley** [codeforkansascity/Neighborhood-Dashboard#42]
Below is a sample wireframe I mocked up that takes a little more advantage of the possible real-estate on a desktop. Any comments, positive or negative? Anyone have any suggestions for mobile?

<img width="1552" alt="wireframe" src="https://cloud.githubusercontent.com/assets/3984979/13589394/38c4062a-e49d-11e5-9ca3-d9ad74cc036b.png">

**Comment by JakeLaCombe** [comment]
Not a huge need or updates for this presently. Closing this issue.
