### ISSUE TITLE
Define Dashboard Purpose

### ISSUE THREAD

**Issue by EricRoche** [codeforkansascity/Neighborhood-Dashboard#5]
Is the dashboard for tracking performance on a specific issue, or is it there to provide general context about the neighborhood?

**Comment by amandaCCF** [comment]
The new neighborhood dashboard would not necessarily track performance on a specific issue, unless the neighborhood is interested in tracking data on their nhood over time. Our target audience is neighborhood associations and organizations that work with nhoods (e.g. Blue Hills Community Services or Legal Aid). The tool will help neighborhoods get the data they need to make better decisions and better advocate for their community.

**Comment by zmon** [comment]
Is this still the same audience that was at the first Focus Group?

**Comment by amandaCCF** [comment]
Yes, the focus group was made of neighborhood representatives and their needs are similar to the needs of the groups that work w them like Blue Hills Community Services and Legal Aid.


________________________________

**Comment by tangospring** [comment]
Nextdoor.com has similar purpose to Neighborhood Dashboard and they apparently figured out how to define neighborhood boundaries on a map from an address.

**Comment by JakeLaCombe** [comment]
I don't think the app is by neighborhood though. I typed in Quality Hill,
and it gave me a map of the entire downtown kc area as opposed to my
neighborhood.

**Comment by lscott1967** [comment]
It is by neighborhood. In fact, you can only join your neighborhood, although the you can choose to interact with people in surrounding neighborhoods. Not sure why it's not working for you, Jake.

**Comment by lscott1967** [comment]
Mystery solved. There is no Quality Hill Neighborhood Association registered with the city.

**Comment by BenCCF** [comment]
NextDoor is really just a neighborhood communication platform. Someone wants to send out an alert about a suspicious person or advertise the neighborhood block party, that's what it's for. We're about getting civic open data clipped to the neighborhood level -- so yes, both this and NextDoor will use neighborhood boundaries, and the audiences might be similar, but the ultimate product/service will be different.

**Comment by zachflanders** [comment]
Nextdoor asks its users to define their neighborhood.  When I signed up
there was no neighborhood in the system for my address, so I drew the
boundaries myself and named my neighborhood.  Once someone establishes a
boundary it knows whether additional address points are within the defined
polygon.  This is a pretty common GIS function.  Turf is a good javascript
library that does this: http://turfjs.org/

Agree that nextdoor and neighborhood dashboard have different functions
(communication tool vs information tool)

**Comment by zachflanders** [comment]
Here the specific function that determines whether a point is within a
polygon: http://turfjs.org/static/docs/module-turf_within.html

**Comment by JakeLaCombe** [comment]
Let's evaulate if that or our current mapping javascript is the right solution. It's not best to have two mapping utilities in the application that do the same thing
