### ISSUE TITLE
Vacant Lot Registry Tab Info

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#54]
[Some Data.xlsx](https://github.com/codeforkansascity/Neighborhood-Dashboard/files/309810/Some.Data.xlsx)

This is excel.doc is just some information I copied and pasted off of the http://webfusion.kcmo.org/coldfusionapps/neighborhood/rentalreg/PropList.cfm site. It's the first 27 rows. (actually the first row got chopped off so it's rows 2-27.)

**Comment by JakeLaCombe** [comment]
Add the tab for this information here.

https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/193ba5e268b14ec990838b67b2a735ab202a32f3

Fixed a Database SQL issue with syntax differences between SQLITE3 and Postgres
https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/89c7a8b7d3b2f9c3327f4986b468931da90ae2fd

**Comment by JakeLaCombe** [comment]
Deployed last night, with database migration and seeds. You can see an example of the data working here http://neighborstat.herokuapp.com/neighborhood/154/vacancies

1. Click on the Filters
2. Choose Registered Vacant

Note: This query takes at least 30 seconds to parse. There are just a lot of addresses that have to be checked. When we go further into production, I think we may want to investigate the possibly of building more data processing scripts.
