### ISSUE TITLE
Footer on the Main Page?

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#55]
What do you think about having the footer on the main page (KCMO: Data Pioneer and How it Works) appear on all pages, no matter which tab you click? Amanda's a fan of the idea. How do you feel about it @JakeLaCombe ?

**Comment by JakeLaCombe** [comment]
We will most likely want to change the content of what's inside as we go from neighborhood to neighborhood. As the footer stands now, it stands as an introduction to what the site is about, and I feel that it disrupts the neighborhood pages by providing the same introductory information.

Perhaps we can instead change those to links to describe what the page is about, or maybe instead add neighborhood specific information to the footer instead?
