### ISSUE TITLE
Adding Address

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#57]
Can we add a property's address to the tooltip? That way users are certain what property they're looking at. I attached an example below.
![mock up](https://cloud.githubusercontent.com/assets/18126988/16458281/2b79665e-3de4-11e6-9a11-8ef29648b092.png)

**Comment by JakeLaCombe** [comment]
Haven't deployed it yet, but I fixed the issue in this commit.

https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/d072e2c09afaf69703709ccf57d683a1eacb4cb1
