### ISSUE TITLE
Adding Vacancy Date

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#58]
For vacant lots and vacant structures, can we list how long it's been vacant in the tooltip?

**Comment by JakeLaCombe** [comment]
We don't have access to that data right now for vacant structures. All I can give you is what you see on this page.

http://webfusion.kcmo.org/coldfusionapps/neighborhood/rentalreg/PropList.cfm

**Comment by JakeLaCombe** [comment]
As for vacant structures, this is the dataset I belive that needs to be used.

https://data.kcmo.org/resource/uv2c-yman.json

What attribute identifies with the structures vacant date?

**Comment by silasck** [comment]
So this data set is just vacant properties that Land Bank has acquired right? If that is the case, the only thing I can see that we could pull for a vacancy date would be the date the property was acquired by Land Bank. I talked with @BenCCF , and we think that may be the best we can do, unless there's a way we can get information from Land Bank about when they started the acquisition process, because  that may be more telling. But I don't know if there is any realistic way of getting that information.

**Comment by JakeLaCombe** [comment]
You'd have to ask Eric Roche on that one.
