### ISSUE TITLE
Legally Abandoned Tab Update 

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#59]
Can we move the two existing filters under "Legally Abandoned" over to Vacant Indicators? And then add the following filters under Legally Abandoned (I'll articulate this better at Hack Night):

- View All Legally Abandoned Properties
           Tax Delinquent
          1.  1-3 Years
          2. 3+ years
           Code Violations
          1. 1-3 Years
          2. 3+ Years
            Vacant
          1. Vacant Properties registry, City of KCMO
          2. Dangerous Building
          3. Open Nuisance Cases/Failure to register as vacant 

![example](https://cloud.githubusercontent.com/assets/18126988/16505303/e4013b9a-3ee1-11e6-9b0b-96cd6245b827.png)

**Comment by JakeLaCombe** [comment]
How do you feel about putting the text underneath the headings into a help
icon with tooltip?

**Comment by silasck** [comment]
Do you mean for the description of legally abandoned and vacant indicators?

**Comment by JakeLaCombe** [comment]
After talking today at the meetup, we redid the position of various filters. The commit to add this can be found here. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/832be671a70191126a57702c80898af79d490cdb
