### ISSUE TITLE
Configure an Azure deployment for application

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/Neighborhood-Dashboard#60]
We are starting to run out of space inside of our box for our free heroku tier. This is causing issues, as we need to store all of the vacant parcels on our application. Azure should allow us to do that

**Comment by zmon** [comment]
@JakeLaCombe we are working on loading vacant parcels into the address api and can keep the shapes.  Let us know if that would be helpful.  @rlh-aagis

**Comment by JakeLaCombe** [comment]
That would definitely help out if the address api can contain those!
