### ISSUE TITLE
Search Function Leniency 

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#62]
Right now the search function for neighborhoods is a little harsh. Misspelling or even not capitalizing the neighborhood name will result in no neighborhood showing up at all. Can we change this so that the search is more friendly? Add a, _"Did you mean ____" kind of function? It may also be helpful to do this for situations with neighborhoods that have added directional names, for example if someone searched 'Paseo' looking for a neighborhood, it would be helpful to say "Did you mean Paseo West or Paseo Neighborhood?" Something to that effect.

**Comment by JakeLaCombe** [comment]
Let's talk about our options for this next week.

**Comment by silasck** [comment]
This is also for memory's sake:
The search style that brings up search options as people type a word out seemed good for now.

**Comment by JakeLaCombe** [comment]
Leinency implemented here - https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/115f1c9c1de21b94a014ba815f102f1e83a43c13
