### ISSUE TITLE
Book Marking

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#65]
Can we add a feature that allows people to save searches? For example, if someone was searching a neighborhood for vacancies and demographics, could we make it so they could save that criteria to return to later? 

Does that make sense?

**Comment by JakeLaCombe** [comment]
Makes perfect sense to me, and I see it as very doable.

However, I need more requirements on how it should handle.

- How should users save their searches?
- What will the UI interactions look and feel like?

**Comment by silasck** [comment]
I wanted to write this here for memory's sake:
Having a 'Saved Search' tab seems like a great way of book marking searches.

**Comment by JakeLaCombe** [comment]
I saw we work with other developers and designers on this feature, and get the idea fleshed out. This isn't a terrible difficult technical enhancement, but it will take a bit of UX work.

**Comment by JakeLaCombe** [comment]
Given that we haven't had any designs come to the developers, I assumed interest in this dropped. Closing
