### ISSUE TITLE
Getting started on demographics tab: Population data

### ISSUE THREAD

**Issue by BenCCF** [codeforkansascity/Neighborhood-Dashboard#66]
Let's get the "Population" section of the demographics tab going. 

The current mockup for the tab is [here](https://www.dropbox.com/s/s0v4qrsvk3g55sh/neighbor%20stat%20demographics%20mockup%206-16-16-02.jpg?dl=0).

The specific data variables we would like displayed are listed [here](https://www.dropbox.com/s/nbx01vqyx3768ag/Census%20variables%20for%20demographics%20tab%207-26%20-Community%20Capital%20Fund%20-%20Lebofsky%20Comments.xlsx?dl=0).

The Excel table with the actual data can be viewed and downloaded [here](https://www.dropbox.com/s/ubyaqy1eh9b59qs/2010Census_2008-2012ACS_byNeighborhood.xlsx?dl=0).

**Comment by JakeLaCombe** [comment]
We are going to need another spreadsheet for the 2000 data as well.

**Comment by amandaCCF** [comment]
Change "Citywide % of Total" column to "City Average"

Change "Neighborhood % of Total" title to "% of Neighborhood"

**Comment by amandaCCF** [comment]
Change "2010 (2008-2012ACS)" to "2010 Census Data (Includes 2010 Decennial Data + 2008-2012 5-Year American Community Survey (ACS) Data)"
