### ISSUE TITLE
Create Navigation System on Each Neighborhood Page

### ISSUE THREAD

**Issue by zachflanders** [codeforkansascity/Neighborhood-Dashboard#7]
Create navigation system for selecting each data source and updating interactive graphs or maps on the page with the data.

**Comment by JakeLaCombe** [comment]
Our goal for this is to create a dynamic element on the page that switches visualizations. Clicking on the navigation switches between the dashboard overview and trending chart that our application provides.

**Comment by JakeLaCombe** [comment]
We went with a tabbed approach for our application. The tabs have crime, vacancy, etc..
