### ISSUE TITLE
Add Homepage Map where all neighborhoods are on the map.

### ISSUE THREAD

**Issue by JakeLaCombe** [codeforkansascity/Neighborhood-Dashboard#72]
It's most likely desirable for an individual to want to see a homepage that outlines all the neighborhoods in the area. In adddition, clicking on one will allow for a user to go to the home page for that particular neighborhood. A mockup can be seen here.
![14625827_10157645009780624_899267048_o](https://cloud.githubusercontent.com/assets/2552573/19216392/3cc0d560-8d7f-11e6-82c8-4ef1b8b95376.jpg)

**Comment by tangospring** [comment]
This can be simple image map.
