### ISSUE TITLE
Good task for new Rails developer?

### ISSUE THREAD

**Issue by ChrisWphoto** [codeforkansascity/Neighborhood-Dashboard#73]
@JakeLaCombe  I am from the UMKC Ethics class and am looking for a api feature or task that I could take on as a new rails developer. 

I have been working in node for for over a year now but am new to rails. 

Can you suggest a task that might be a good fit?

**Comment by JakeLaCombe** [comment]
It's hard to point out good beginner tasks, as a lot of them are very complex. I'll try to see what I can find when the MVP is ready, but I can't promise dedicated beginner issues

**Comment by JakeLaCombe** [comment]
I'll close this, but feel free to message me if you'd like other issues. I'll see what comes up.
