### ISSUE TITLE
MVP: Upload 1990-2000 Census Data to Demographics Tab

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#74]
Steve Lebofsky sent over census data for 1990-2000 in an excel file (woohooo!) Where would it be best for me to put that file?

**Comment by silasck** [comment]
[1990-2000 Census Data.xlsx](https://github.com/codeforkansascity/Neighborhood-Dashboard/files/551378/1990-2000.Census.Data.xlsx)

**Comment by JakeLaCombe** [comment]
@AmandaWilsonKC @silasck is asking to display the data in this similar fashion. https://www.portlandoregon.gov/oni/article/376013. Do you have any thoughts on this?

**Comment by JakeLaCombe** [comment]
@silasck What do the dashes in the spreadsheet mean? Does that imply a 0 for that value, which I think is incorrect?

**Comment by JakeLaCombe** [comment]
Upload here. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/ad1ec7f334f35d48fe1f63ddedd4a6cf24a8a2fb. We can do further debugging on future issues
