### ISSUE TITLE
MVP: Change Column Titles in Demographic Tab

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#75]
Change "Citywide % of Total" column to "City Average"
Change "Neighborhood % of Total" title to "% of Neighborhood"

Change "2010 (2008-2012ACS)" to "2010 Census Data (Includes 2010 Decennial Data + 2008-2012 5-Year American Community Survey (ACS) Data)"

**Comment by JakeLaCombe** [comment]
Done Here - https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/c9d5bea1d4667383e793ad4fc59fa0860c59d614
