### ISSUE TITLE
MVP :) Missing Income Information

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#77]
We're missing income data, here's a spreadsheet that has the missing info:
Under the Education/Employment part there is a section called Household Income, I think that's what's missing.

https://www.dropbox.com/s/ys7s123kzvc6qxa/Census%20variables%20for%20demographics%20tab%207-26%20-Community%20Capital%20Fund%20-%20Lebofsky%20Comments.xlsx?dl=0

**Comment by JakeLaCombe** [comment]
I can't give you your desired household income categories, as your 2000 data does not have the data split between 10,000-15,000 and 15,000-20,000. It just does $10,000-$20,000. I'll do that instead, but I recommend updating your spreadsheet to do so.

**Comment by JakeLaCombe** [comment]
Done - https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/e9c2c710b06632daeae40d3eca78e18d95cd201e
