### ISSUE TITLE
MVP ISSUES #thistimeitsreal

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#78]
1. West Bottoms is not recognized as neighborhood 
2. There's no neighborhood data from Truman Rd to 19th, Troost to Paseo
3. Silas will add more

**Comment by JakeLaCombe** [comment]
We would need to consult with @codeforkansascity/c4kc-core-team on this most likely. I can only work with the data provided by this API or the datasets that are offered to us.

**Comment by AmandaWilsonKC** [comment]
Additional MVP Updates:
1. Add the source of each dataset in parenthesis - this info is already included in the "Filter Category Name" Column in the Dataset Attributes spreadsheet. E.g. - for the Vacant Lot dataset, it is listed as "Vacant Lot (KCMO Land Bank Property)" . "Vacant Lot" appears as the dataset in our app but we need to add "(KCMO Land Bank Property)" so people know the source of the data.

2. Legend/key for the Vacancy tab.

3. Add Tax Delinquency dataset to the Vacant Indicators list. Add Dangerous Buildings dataset to the Vacant Indicators list. 

4. What is "All Property Violations" dataset listed under the Vacant Indicators list?? This is not listed in the Dataset Attributes spreadsheet. Is it supposed to be the "Vacant + Boarded - Property Violations (City of KCMO)" dataset? The name of the dataset should be changed to how it is listed in the Dataset Attributes spreadsheet. 

5. What exactly are the two Demographic datasets being brought in? I thought we were bringing in 2008-2012 and 2010? Is that right? If so, the column names should be changed to reflect the exact date ranges.

**Comment by JakeLaCombe** [comment]
@amandaCCF The two datasets are 2000 and 2010 Census Data. I take it you wish to have the comparison between the 2008-2012 ACS and the 2010 Census? If so, I'll need help getting that data. @silasck

**Comment by JakeLaCombe** [comment]
Some more questions @amandaCCF @silasck

1. We have that in the legally abandoned data. I take it you want it added to the Vacant Indicators?

3. We have that data on the left side already. Wouldn't it get confusing if we have the same data in two different locations? 

4. The All Property Violations is currently a filter that finds any other violations that we didn't specify on the left or right side. So if 'Overflowing Garbage' came up as a code violation and we didn't add it to our application, it would show up. Perhaps it should be renamed to other filters?

**Comment by AmandaWilsonKC** [comment]
@zmon and @rlh-aagis - vacancy data for several neighborhoods (Indian Mound, Scarritt) is not showing up. Help!

**Comment by AmandaWilsonKC** [comment]
Rename Demographic Column 2010 to 2008-2012 ACS. Keep 2000 Census column name.

**Comment by JakeLaCombe** [comment]
And here is the final addition, adding full address to the tooltip. This issue is finally wrapped up! https://github.com/codeforkansascity/Neighborhood-Dashboard/issues/89

As for displaying all the code violations, I think we are going into both technical and usability issues. Technically, it will take a long time to get all that data back from the service. Right now, we just return the counts, which is a much lower cost than returning the entire data. For Usability, our tooltips are getting pretty large, and having a scrollable tooltip is not recommended. It's defeating the purpose of the tooltip. We can definitely look at it more in the future, but it's best to leave it off for now.
