### ISSUE TITLE
Redesign Neighborhood Visuals

### ISSUE THREAD

**Issue by HDoug123** [codeforkansascity/Neighborhood-Dashboard#8]
Neighborhood Visuals - Data for Neighborhood Graphs
![img_0965](https://cloud.githubusercontent.com/assets/12903451/8421644/763f7632-1e97-11e5-9a66-a61dc35a6927.JPG)

**Comment by amandaCCF** [comment]
A few of the items on this sheet - traffic, walkability, parks - are new and were not identified by our neighborhood groups as a priority to include in the dashboard. What's the intention with these?

**Comment by JakeLaCombe** [comment]
For us, we were just grabbing what we would see as potential datasets that could be asked upon in the future. We will only be incorporating data sets that your neighborhood groups identify as a priority.

**Comment by amandaCCF** [comment]
Great, thanks! I think we'll be meeting again with the neighborhoods in late July/early August to get more feedback from them on the type of data they'd like to use. We can talk about a timeline for neighborhood input tonight or the next meetup.

**Comment by JakeLaCombe** [comment]
We've re designed the app back in September. We can close this.
