### ISSUE TITLE
Problem identification 

### ISSUE THREAD

**Issue by silasck** [codeforkansascity/Neighborhood-Dashboard#80]
The site needs to be tested, poked around on, and otherwise messed with in order to identify problems, bugs, or errors.

**Comment by AmandaWilsonKC** [comment]
There are number of neighborhoods that are showing ZERO legally abandoned properties. That can't be right. Troubleshoot neighborhoods: Scarritt, North Indian Mound, South Indian Mound, Washington Wheatley.

**Comment by JakeLaCombe** [comment]
@AmandaWilsonKC I believe it is an issue with the address api. I'm not seeing data for several neighborhoods.

@zmon can we sync up soon? I want to make sure I'm consuming the API correctly. The line of code to retrieve addresses can be found here. https://github.com/codeforkansascity/Neighborhood-Dashboard/blob/master/app/models/neighborhood.rb#L23

**Comment by gregbonner** [comment]
This turned out to be a data issue in the AddressAPI.  Some of our neighborhoods are spelled differently in the database than their official names.  I'll let you know when we have this fixed on our end.

**Comment by JakeLaCombe** [comment]
Looks like all the work is done here for this issue. Closing
