### ISSUE TITLE
Apps loads half of the time

### ISSUE THREAD

**Issue by Andrewvanbeek** [codeforkansascity/Neighborhood-Dashboard#81]
Not sure if this is something that has been pointed out, but the map loads half of the time.  Additionally in the JS console I get ReferenceError: google is not defined.

**Comment by JakeLaCombe** [comment]
Try this fix. I think it may have resolved this issue. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/ade975cbf97302d8f28a8e87506550ba640f2ea4
