### ISSUE TITLE
Drawing polygon or overlaying other geographies?

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#83]
how difficult would it be to have our tool have the capability to draw a polygon over an area and pull in data in just that area? 

Follow up question, how difficult would it be to add other geographic boundaries like council districts and have our tool pull data in just that boundary?

This is NOT needed for the MVP but would be great for version #2 or 3.

**Comment by JakeLaCombe** [comment]
We'd have to determine what colors we want to ensure they do not collide, but I think it would be possible.

**Comment by JakeLaCombe** [comment]
As for pulling in the other boundaries, it's possible with any data from the socrata API's, but I don't know how well it will work with the address-api. It doesn't take in a set of coordinates to get all the data that lies within that range, and instead bases it's selection on the neighborhood passed into the API

**Comment by JakeLaCombe** [comment]
Is this for drawing one inside an individual neighborhood? If so, that could be doable.

**Comment by JakeLaCombe** [comment]
Update. I've asked the address api to include the ability to filter addresses by polygon region. You can track that here. 

https://github.com/codeforkansascity/address-api/issues/123
