### ISSUE TITLE
Add owner name to tooltip

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#84]
Can we add the owner name to the tooltip on the Vacancy tab for parcels? Would be helpful to see if the owner is an individual or a corporation.

**Comment by JakeLaCombe** [comment]
I can only add it for parcels that are registered vacant. If it's not, then I am unable to find the owner for a given partial.

**Comment by JakeLaCombe** [comment]
Added fully now! https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/40a1eaa7ecbbfcfa3c9062167f47af2d6d341627
