### ISSUE TITLE
Consider using sparkle charts in the dashboard

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/Neighborhood-Dashboard#9]
Sparkle charts have good information density for displaying data change over time. These are great for viewing and analyzing multiple trends.

**Comment by JakeLaCombe** [comment]
Can you provide a link to sparklecharts that would be great for the application?

**Comment by tangospring** [comment]
Google Chart API, Sparkline PHP Graphing Library, JQuery Sparklines support sparkle charts: https://en.wikipedia.org/wiki/Sparkline

**Comment by tangospring** [comment]
Here is another example illustrating trends in multiple sparkle charts: http://githut.info/ (scroll down to the second screen).

**Comment by JakeLaCombe** [comment]
There hasn't been discussion on this, so let's go ahead and close it. We can come back to it later, but it's not applicable for current state of the application.
