### ISSUE TITLE
Add date picker widget for filters [ui improvement] 

### ISSUE THREAD

**Issue by jmansilla** [codeforkansascity/Neighborhood-Dashboard#91]
Both when looking for crime events , or vacancies, there are some _date input fields_  for setting some range in order to filter the query.

Instead of them been just free text fields, could be easier to use with some date picker widget. For instance, this one https://bootstrap-datepicker.readthedocs.io/en/latest/ (there are tons of similar widgets)

**Comment by JakeLaCombe** [comment]
It works on chrome, as that has a default datetime picker that we can use. When I get the app refactored to react, this will make this issue easier.

**Comment by JakeLaCombe** [comment]
Fixed - https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/865131eeb0c25a8e6bcad364bde3e0596b54e593
