### ISSUE TITLE
Link to New URL

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#93]
CCF has purchased new url - www.kcneighborhoodstat.org. Now what?

**Comment by JakeLaCombe** [comment]
I'll see what we can do to deploy to an azure box, and then link to that website. I maybe able to do it from heroku as well.

**Comment by JakeLaCombe** [comment]
It's live!

http://www.kcneighborhoodstat.org/
