### ISSUE TITLE
Delete Rental/Vacant Property Registration Dataset

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#96]
Please delete the Rental/Vacant Property Registration Dataset - http://webfusion.kcmo.org/coldfusionapps/neighborhood/rentalreg/PropList.cfm. It shows up as "Registered Vacant (City of KCMO)" in both the Legally Abandoned list and the Vacant Indicators list. For the Legally Abandoned, take it out of calculation too. Thanks!

**Comment by JakeLaCombe** [comment]
Gone. https://github.com/codeforkansascity/Neighborhood-Dashboard/commit/80515da3d879a1f5ac72a91e05bb72e96a48d6c6
