### ISSUE TITLE
List of Nhood Boundaries that are "wrong"

### ISSUE THREAD

**Issue by AmandaWilsonKC** [codeforkansascity/Neighborhood-Dashboard#98]
I'm starting a list of the neighborhood boundaries that are in dispute or wrong. The boundaries are pulled from the City so we should see what it takes for them to change these.

1. Independence Plaza - Independence Plaza Neighborhood boundaries include from Brooklyn to The Paseo between 9th and Independence Avenue.  

... more to come I'm sure...

**Comment by JakeLaCombe** [comment]
This will have to be an issue we forward to Eric.

**Comment by AmandaWilsonKC** [comment]
Turns out the city has a form for neighborhoods to complete when they have a dispute with their boundaries. I have the word docs for it but I think I'll direct people to Sarah Cecil at the City to get the forms. I'll include this info in the About or the About the Data text.
